### ISSUE TITLE
[BUG] chown 2500 in the docs breaks functionality on Mac

### ISSUE THREAD

**Issue by dukejones** [ray-rock/containarr#31]
# Necessary Information

### Please do not omit these categories.

- Operating System: Mac Monterey M1
- Containarr Version: main branch, Mar 30 2022
- Docker Version: 20.10.12
- Docker Compose Version: n/a

# Logging

### Please attach any logs if possible. 

# Description

### Describe the bug to the best of your ability.

When following the instructions the chown 2500 command makes it so that the various containers do not have write access to the data directories. Apparently this is because on the Mac docker utilizes NFS for attaching volumes, which automatically sets the user & group correctly. 

When I change the ownership back to my own user in group, and restarted all the containers, the problem was fixed.

# Reproduction

chown -R 2500 data/
docker exec -it sonarr bash
touch /data/sonarr/hello.txt # error!

### If you know how to reproduce the bug, list steps below.

# Expected Behavior
Able to write
### Describe expected behavior below.

# Additional Information

chown back to your user & group and it works

**Comment by ray-rock** [comment]
Thank you for logging this issue, I don't own any apple machines so your input here is greatly appreciated. A pr will be opened soon.
