### ISSUE TITLE
deemix - variables

### ISSUE THREAD

**Issue by Bockiii** [ray-rock/containarr#5]
Hi,

You can remove the 'umask' setting and just keep 'UMASK_SET'. Umask is not picked up.

You could also add "-e DEEMIX_SINGLE_USER=true" as that will make the login serverwide (so you only need to login once in one browser and can use the same user in every session)

**Comment by ray-rock** [comment]
@Bockiii, 

Thanks for stopping by, I appreciate the contributions! I've added your suggestions to my workflow and will close this issue once the branch has been merged. 



p.s. thank you for deemix-docker!

**Comment by ray-rock** [comment]
Issue has been addressed and suggestions were implemented in v0.1.1. Thank you!
