### ISSUE TITLE
improvement of mounts to allow hardlinking

### ISSUE THREAD

**Issue by stevietv** [ray-rock/containarr#8]
When mounting `/downloads` and `/media` as two separate volumes, you are creating two separate file systems within the containers, causing all files to be duplicated when moved instead of hardlinks. 

The trash guides (https://trash-guides.info/Hardlinks/Hardlinks-and-Instant-Moves/) provide an optimal set up for volumes to save on disk space (when seeding) and disk writes (using atomic moves and hardlinking instead of copies).

A recommended structure would be to mount a single volume `/data`  and store in that your downloads and your library. for example:
```
data
├── torrents
│  ├── movies
│  ├── music
│  └── tv
├── usenet
│  ├── movies
│  ├── music
│  └── tv
└── media
   ├── movies
   ├── music
   └── tv
```

Individual apps can be given the correct structure, eg sonarr gets mounted the volume `/data:/data` whereas qbittorrent gets `/data/torrents:/data/torrents`

**Comment by ray-rock** [comment]
This is a major oversight on my part. I've made this a high priority fix and will work to merge one as soon as possible.

**Comment by ray-rock** [comment]
This is solved in pr #21. This issue is now closed.

**Comment by stevietv** [comment]
I would still say there is some work to do. see my review: https://github.com/ray-rock/containarr/pull/21#pullrequestreview-922297868_

**Comment by ray-rock** [comment]
Totally missed this. I'll have to make sure to keep collaborators in mind before closing issues. I've only collaborated with myself on gitea before now, my bad!! 

I'll be addressing your review in v0.2.3

**Comment by ray-rock** [comment]
# note to self
Remember to pace yourself when working on projects with multiple collaborators. Don't just rush through the review process on prs that involve issues brought up by, or involving input of others; Leave time for them to review before rushing to make a new release. There's no need to rush. Quality of releases/commits over quantity! Always remember this.

**Comment by stevietv** [comment]
love this! I am exactly the same!

> # note to self
> Remember to pace yourself when working on projects with multiple collaborators. Don't just rush through the review process on prs that involve issues brought up by, or involving input of others; Leave time for them to review before rushing to make a new release. There's no need to rush. Quality of releases/commits over quantity! Always remember this.

**Comment by ray-rock** [comment]
> love this! I am exactly the same!
> 
> > # note to self
> > Remember to pace yourself when working on projects with multiple collaborators. Don't just rush through the review process on prs that involve issues brought up by, or involving input of others; Leave time for them to review before rushing to make a new release. There's no need to rush. Quality of releases/commits over quantity! Always remember this.

😁

This is a lifelong struggle for me as well, so I'm glad you understand!

**Comment by ray-rock** [comment]
# Back to task

PR #27 appears to satisfy this issue, and is ready to be merged. I will merge to main and close this issue in one hour at 8:10pm PDT

**Comment by ray-rock** [comment]
I will leave this issue unlocked for one week.
